#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
cd "$ROOT_DIR"

ENV_FILE=${ENV_FILE:-.env.quickstart}
APP_PORT=${APP_PORT:-3000}
PROJECT_NAME=${COMPOSE_PROJECT_NAME:-sveltekit-learning-lab-quickstart}

fail() {
	echo "quickstart: $*" >&2
	exit 1
}

command -v docker >/dev/null 2>&1 || fail "Docker is required: https://docs.docker.com/engine/install/"
docker compose version >/dev/null 2>&1 || fail "The Docker Compose plugin is required."

if [[ ! "$APP_PORT" =~ ^[0-9]+$ ]] || ((APP_PORT < 1 || APP_PORT > 65535)); then
	fail "APP_PORT must be a number between 1 and 65535."
fi

if [[ ! -f "$ENV_FILE" ]]; then
	umask 077
	password=$(od -An -N24 -tx1 /dev/urandom | tr -d ' \n')
	cat >"$ENV_FILE" <<EOF
# Generated by scripts/quickstart.sh. This file is ignored by Git.
APP_VERSION=quickstart
APP_PORT=$APP_PORT
COMPOSE_PROJECT_NAME=$PROJECT_NAME
ORIGIN=http://localhost:$APP_PORT

POSTGRES_DB=sveltekit_learning_lab
POSTGRES_USER=sveltekit
POSTGRES_PASSWORD=$password
DATABASE_URL=postgresql://sveltekit:$password@db:5432/sveltekit_learning_lab

SHUTDOWN_TIMEOUT=30
BODY_SIZE_LIMIT=512K
EOF
	echo "Created $ENV_FILE with a random local database password."
else
	echo "Reusing $ENV_FILE."
fi

chmod 600 "$ENV_FILE"

# Compose gives exported shell variables precedence over --env-file. Remove values
# from the caller so the generated, project-local environment stays reproducible.
env \
	-u APP_VERSION \
	-u APP_PORT \
	-u COMPOSE_PROJECT_NAME \
	-u ORIGIN \
	-u POSTGRES_DB \
	-u POSTGRES_USER \
	-u POSTGRES_PASSWORD \
	-u DATABASE_URL \
	-u SHUTDOWN_TIMEOUT \
	-u BODY_SIZE_LIMIT \
	-u COMPOSE_FILE \
	ENV_FILE="$ENV_FILE" \
	scripts/deploy.sh --seed

configured_port=$(awk -F= '$1 == "APP_PORT" { print $2; exit }' "$ENV_FILE")
configured_port=${configured_port:-$APP_PORT}

cat <<EOF

SvelteKit Learning Lab is ready.
  Open: http://localhost:$configured_port
  Stop: docker compose --env-file $ENV_FILE -f compose.production.yml down
  Start again: ./scripts/quickstart.sh
EOF
